HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
content-encoding: gzip
Transfer-Encoding: chunked

{"data": {"me": {"profile": {"topArtists": {"__typename": "ArtistPageV2","items": [{"data": {"__typename": "Artist","profile": {"name": "Taylor Swift"},"uri": "spotify:artist:06HL4z0CvFAxyc27GXpf02"
                            }
                        }
                    ],
                    "totalCount": 1
                }
            }
        }
    }
}