name: circom

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install
        npm install -g snarkjs

    - name: Download and install Circom
      run: |
        CIRCOM_VERSION=2.1.9
        curl -L https://github.com/iden3/circom/releases/download/v$CIRCOM_VERSION/circom-linux-amd64 -o circom
        chmod +x circom
        sudo mv circom /usr/local/bin/
        circom --version

    - name: ls
      run: ls
    - name: pwd
      run: pwd
    # - name: Run tests
    #   run: npm run test
    - name: Print Folder Tree
      uses: jaywcjlove/github-action-folder-tree@main
      with:
        exclude: "node_modules|dist|.git|.husky"
